### ISSUE TITLE
Хоткей

### ISSUE THREAD

**Issue by Kamui-Solo** [kosmodrey/uNote#10]
Я думаю полезно было бы сделать настройку горячих клавиш, для самостоятельного выбора хоткея во избежание конфликтов.

**Comment by kosmodrey** [comment]
Если я Вас правильно понял, то такая возможность уже присутствует в настройках:

![cjq8i 2015-03-29 12 22 47](https://cloud.githubusercontent.com/assets/10274725/6884884/c478e300-d60e-11e4-8121-01e1bd5efe33.png)

**Comment by Kamui-Solo** [comment]
Точно, вот я балда, лазил же в настройки, но не запомнил что там видел:D
