### ISSUE TITLE
Менеджер заметок

### ISSUE THREAD

**Issue by Kamui-Solo** [kosmodrey/uNote#15]
Я думаю стоит добавить какую-то кнопку для открытия менеджера заметок из всплывающего окна с заметками.

**Comment by kosmodrey** [comment]
С появлением кнопки "глобальные заметки", появилось дополнительное место. Так как и настройки переносятся в отдельный таб (#13), можно будет сделать нечто такое:

![](https://cloud.githubusercontent.com/assets/10274725/7105714/c7486b48-e12e-11e4-811d-430e522130b4.png)

Там где синий - кнопка редактора, красный - настройки.

**Comment by Kamui-Solo** [comment]
Думаю так было бы отлично;)
