### ISSUE TITLE
Не сохраняются

### ISSUE THREAD

**Issue by Kamui-Solo** [kosmodrey/uNote#16]
В новой версии не сохраняются заметки, я как-то игрался с настройками и после включения "Open pinned notes" перестали сохраняться заметки.

**Comment by kosmodrey** [comment]
Попробуйте нажать на _Control + Shift + J_ для просмотра ошибок в консоли. Есть ли там что-то связанное с аддоном?

Недавно я только узнал, что [simple-storage](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-storage) не самое надёжное место, так как при "неожиданном" закрытии браузера, новые изменения в базе не будут сохранены в файловой системе. Может, по этой причине у Вас возникли проблемы?

**Comment by Kamui-Solo** [comment]
В консоли ничего не пишет, но я выяснил причину несохранения заметок. Дело в том что я вставляю заметки с помощью колеса мыши, при включённой в about:config настройке middlemouse.paste
Если вручную напечатать или вставить с ctrl+v, то все сохраняется.

**Comment by kosmodrey** [comment]
Спасибо, подправил.
Если нужна свежая сборка, то она тут: https://yadi.sk/d/RCXsySgWg64B7

**Comment by Kamui-Solo** [comment]
Отлично работает, благодарю:) и за уже упакованное расширение тоже;)
