### ISSUE TITLE
Восстановление без бекапа

### ISSUE THREAD

**Issue by JaPyR** [kosmodrey/uNote#31]
Здрасте, есть ли возможность восстановить заметки без бекапа имя доступ только ко всему содержимому профиля firefox?

**Comment by kosmodrey** [comment]
Здравствуйте,

Для сохранения заметок, uNote использует IndexedDB. Файл базы данных сохраняется в папке каждого профиля, по пути `\storage\permanent\indexeddb+++unote-at-kosmodrey`. Вы можете делать резервные копии данной папки или переносить в другие профили Firefox.
