### ISSUE TITLE
Global notes

### ISSUE THREAD

**Issue by Kamui-Solo** [kosmodrey/uNote#8]
Please implement switcher to global notes. For example I save note on some site and go to another, then open note in this site and use note as I wish on this site.
May be it can be switcher in options, something like "per-site notes" and "global notes".

**Comment by kosmodrey** [comment]
Thanks for suggestion. This will be a good small feature.

**Comment by Kamui-Solo** [comment]
Or may be create two separated parts in one popup for global and per-site notes.

**Comment by kosmodrey** [comment]
Added toggle button on notes panel. You can easily switch between global and per-site notes.

![global](https://cloud.githubusercontent.com/assets/10274725/6865212/3b6dafc8-d474-11e4-939b-ed23eaa7581b.png)

What do you think?

**Comment by Kamui-Solo** [comment]
Briliant idea, but does this toggler save it's state? And how i can try updated version?

**Comment by kosmodrey** [comment]
Yes, toggle will save the global notes state.
You can download and test last build (.xpi) here: https://yadi.sk/d/dBOFLHrxfZHtD (drag and drop file to Firefox window and install it). Or you can build by yourself using Firefox add-on sdk tool: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx

**Comment by Kamui-Solo** [comment]
Thanks, excellent realization.

**Comment by Kamui-Solo** [comment]
One moment, when I choose global notes and there is no notes, it says "No notes for this site yet", but must be something like "No global notes".

Samoe zabovnoe chot dva russkogovoryaschih cheloveka obschayutsya na angliyskom yazike:)

**Comment by kosmodrey** [comment]
Спасибо, исправил недочёт с надписью :)
